<a href="https://colab.research.google.com/github/oxanaRC/CE888/blob/master/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#lab1
#q1
import numpy as np
myArray=np.array([[1,2,3,4],[5,6,7,8]])
print(myArray)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
#q2
myArray2=np.array([[0,1,2,3,4,6,7,4,8,5]])
print(myArray2.shape)
myArray2Sort1=np.sort(myArray2)
print(myArray2Sort1)
myArray2Sort2=myArray2Sort1[:,::-1]
print(myArray2Sort2)

(1, 10)
[[0 1 2 3 4 4 5 6 7 8]]
[[8 7 6 5 4 4 3 2 1 0]]


## Questions to be done during the lab:

1. Create a (4 x 2) integer array and print it's attributes

2. Create an array of dimension (1,10) and sort it in ascending and descending order

3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

4. Stack two arrays of any size horizontally and vertically

5. Create two array of same size and find commom elements

6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

7. Create an array of size 100 and  compute the mean, median, standard deviation. 

8. Normalize a 5x5 random matrix 

9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

