<a href="https://colab.research.google.com/github/oxanaRC/CE888/blob/master/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#lab1
#q1
import numpy as np
myArray=np.array([[1,2,3,4],[5,6,7,8]])
print(myArray)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
#q2
myArray2=np.array([[0,1,2,3,4,6,7,4,8,5]])
print(myArray2.shape)
myArray2Sort1=np.sort(myArray2)
print(myArray2Sort1)
myArray2Sort2=myArray2Sort1[:,::-1]
print(myArray2Sort2)

(1, 10)
[[0 1 2 3 4 4 5 6 7 8]]
[[8 7 6 5 4 4 3 2 1 0]]


In [4]:
#q3
myArray3=np.array([1,2,3,4,5,6,7,8,9])
myArray3Reshaped=np.reshape(myArray3,(3,3))
print(myArray3Reshaped)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#q4
myArray41=np.array([1,2,3,4])
myArray42=np.array([4,5,6,7])
myArray4h=np.stack((myArray41,myArray42))
print(myArray4h)
myArray4v=np.stack((myArray41,myArray42),axis=-1)
print(myArray4v)

[[1 2 3 4]
 [4 5 6 7]]
[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [6]:
#q5
myArray51=np.array([1,2,3,9,4,10])
myArray52=np.array([4,5,6,9,10,7])
myArray5c=np.intersect1d(myArray51,myArray52)
print(myArray5c)



[ 4  9 10]


In [7]:
#q6
myArray6=np.random.rand(5,5)
print(myArray6)
print(np.amax(myArray6))

print(myArray6.min(axis=1))
print(myArray6.max(axis=1))

print(myArray6.min(axis=0))
print(myArray6.max(axis=0))



[[0.49548783 0.50677499 0.42149506 0.47665644 0.13721725]
 [0.07739966 0.13024271 0.51361405 0.59390112 0.72316438]
 [0.69603494 0.96663574 0.67386494 0.32360006 0.43337774]
 [0.78619219 0.62143068 0.648362   0.16526043 0.22087714]
 [0.2357988  0.51303607 0.73852528 0.88408601 0.52509743]]
0.9666357404679098
[0.13721725 0.07739966 0.32360006 0.16526043 0.2357988 ]
[0.50677499 0.72316438 0.96663574 0.78619219 0.88408601]
[0.07739966 0.13024271 0.42149506 0.16526043 0.13721725]
[0.78619219 0.96663574 0.73852528 0.88408601 0.72316438]


In [8]:
#q7
myArray7=np.random.rand(100)
print(np.mean(myArray7))
print(np.median(myArray7))
print(np.std(myArray7))


0.5045846167104918
0.4751817070323822
0.2946726659468264


In [17]:
#q8
myArray8=np.random.rand(5,5)
print(myArray8)
print("-------------")
print(np.linalg.norm(myArray8,axis=1,ord=2,keepdims=True))
print("------------")
print(myArray8/np.linalg.norm(myArray8, ord=2, axis=1, keepdims=True))



[[0.66691736 0.5689136  0.68078825 0.29989021 0.60121979]
 [0.70119186 0.23786439 0.86777933 0.61267426 0.64242288]
 [0.11523502 0.53351876 0.56503104 0.43100901 0.76646737]
 [0.85112164 0.82229467 0.61438767 0.18440938 0.21689276]
 [0.98176102 0.03590538 0.73205776 0.27416939 0.09144111]]
-------------
[[1.29742571]
 [1.44546441]
 [1.17916176]
 [1.36348747]
 [1.25880212]]
------------
[[0.51403125 0.43849417 0.52472234 0.23114249 0.46339438]
 [0.48509797 0.16455915 0.60034638 0.4238598  0.44444047]
 [0.09772622 0.45245596 0.47918026 0.36552153 0.65001037]
 [0.62422403 0.60308194 0.45060016 0.13524831 0.15907206]
 [0.77991688 0.02852345 0.5815511  0.21780182 0.07264137]]


In [0]:
#q9
myArray91=np.random.rand(4,4,3)
myArray92=np.random.rand(4,4)
#to be finished
#for i in range ()
#print(len(myArray91))


## Questions to be done during the lab:

1. Create a (4 x 2) integer array and print it's attributes

2. Create an array of dimension (1,10) and sort it in ascending and descending order

3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

4. Stack two arrays of any size horizontally and vertically

5. Create two array of same size and find commom elements

6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

7. Create an array of size 100 and  compute the mean, median, standard deviation. 

8. Normalize a 5x5 random matrix 

9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

