<a href="https://colab.research.google.com/github/oxanaRC/CE888/blob/master/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#lab1
#q1
import numpy as np
myArray=np.array([[1,2,3,4],[5,6,7,8]])
print(myArray)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
#q2
myArray2=np.array([[0,1,2,3,4,6,7,4,8,5]])
print(myArray2.shape)
myArray2Sort1=np.sort(myArray2)
print(myArray2Sort1)
myArray2Sort2=myArray2Sort1[:,::-1]
print(myArray2Sort2)

(1, 10)
[[0 1 2 3 4 4 5 6 7 8]]
[[8 7 6 5 4 4 3 2 1 0]]


In [24]:
#q3
myArray3=np.array([1,2,3,4,5,6,7,8,9])
myArray3Reshaped=np.reshape(myArray3,(3,3))
print(myArray3Reshaped)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
#q4
myArray41=np.array([1,2,3,4])
myArray42=np.array([4,5,6,7])
myArray4h=np.stack((myArray41,myArray42))
print(myArray4h)
myArray4v=np.stack((myArray41,myArray42),axis=-1)
print(myArray4v)

[[1 2 3 4]
 [4 5 6 7]]
[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [31]:
#q5
myArray51=np.array([1,2,3,9,4,10])
myArray52=np.array([4,5,6,9,10,7])
myArray5c=np.intersect1d(myArray51,myArray52)
print(myArray5c)



[ 4  9 10]


In [38]:
#q6
myArray6=np.random.rand(5,5)
print(myArray6)
print(np.amax(myArray6))

print(myArray6.min(axis=1))
print(myArray6.max(axis=1))

print(myArray6.min(axis=0))
print(myArray6.max(axis=0))



[[0.20995715 0.29384096 0.32893203 0.26657386 0.01587098]
 [0.12033257 0.9259902  0.81957442 0.01730133 0.71530031]
 [0.90583045 0.2279189  0.63899677 0.38408879 0.01617929]
 [0.5087062  0.76150745 0.32880596 0.64554311 0.37713249]
 [0.68947814 0.13337468 0.36362289 0.78213621 0.72764585]]
0.9259902036478177
[0.01587098 0.01730133 0.01617929 0.32880596 0.13337468]
[0.32893203 0.9259902  0.90583045 0.76150745 0.78213621]
[0.12033257 0.13337468 0.32880596 0.01730133 0.01587098]
[0.90583045 0.9259902  0.81957442 0.78213621 0.72764585]


## Questions to be done during the lab:

1. Create a (4 x 2) integer array and print it's attributes

2. Create an array of dimension (1,10) and sort it in ascending and descending order

3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

4. Stack two arrays of any size horizontally and vertically

5. Create two array of same size and find commom elements

6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

7. Create an array of size 100 and  compute the mean, median, standard deviation. 

8. Normalize a 5x5 random matrix 

9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

